### Slice in arrays (2d e 3d)

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4],[5,6]])

In [8]:
array_sliced = a[1:,1:]

In [9]:
print(array_sliced)

[[4]
 [6]]


In [11]:
b = np.array([[1,2,3,4],[5,6,7,8],[20,30,40,50]])

In [12]:
b_sliced = b[1:,1:]

In [13]:
print(b_sliced)

[[ 6  7  8]
 [30 40 50]]


In [ ]:
a[:,:1,]

### 3d Arrays

A 3º dimensão é a primeira posição do slice

podemos visualizar como:
- dimensão de profundidade
- dimensão de linhas
- dimensão de colunas

na ordem do slice, ficará 
array[profundidade, linhas, colunas]

In [14]:
d = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

In [18]:
print(d[:,1:,1:])

[[[3]]

 [[7]]]
